logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN

server:
  port: 8080
  servlet:
    context-path=/hkstockoption/api:

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      idle-timeout: 10000

